const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Tilemap,
		C3.Behaviors.Pin,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Keyboard.Acts.LockKeyboard,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.JavaScriptInEvents.EventSheet1_Event37_Act2,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Mouse.Cnds.OnClick
	];
};
self.C3_JsPropNameTable = [
	{podetomardano: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Solid: 0},
	{Flash: 0},
	{JOGADOR: 0},
	{Keyboard: 0},
	{Tilemap: 0},
	{DIRECAO: 0},
	{ESQUELETADO: 0},
	{Sensor: 0},
	{SENSOR_ESQUELETA_DIREITA: 0},
	{SENSOR_ESQUELETA_ESQUERDA: 0},
	{Pin: 0},
	{VIDA_HUD: 0},
	{BACKGROUND: 0},
	{Bullet: 0},
	{Fade: 0},
	{Tween: 0},
	{SLASH: 0},
	{Particles: 0},
	{DEATHFORADOMAPA: 0},
	{explosion: 0},
	{Sprite: 0},
	{Particles2: 0},
	{Sprite2: 0},
	{BACKGROUND2: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite3: 0},
	{Sprite8: 0},
	{Audio: 0},
	{Sprite9: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Particles3: 0},
	{Sprite4: 0},
	{Sprite10: 0},
	{ESQUELETADO2: 0},
	{Sprite15: 0},
	{NightWalker: 0},
	{Button: 0},
	{Sprite16: 0},
	{Particles4: 0},
	{Particles5: 0},
	{Particles6: 0},
	{Particles7: 0},
	{Particles8: 0},
	{Sprite17: 0},
	{Button2: 0},
	{Mouse: 0},
	{Sprite18: 0},
	{Sensor2: 0},
	{Particles9: 0},
	{Sprite14: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{RECOMEÇAR: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Vidas: 0}
];

self.InstanceType = {
	JOGADOR: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	ESQUELETADO: class extends self.ISpriteInstance {},
	Sensor: class extends self.ISpriteInstance {},
	SENSOR_ESQUELETA_DIREITA: class extends self.ISpriteInstance {},
	SENSOR_ESQUELETA_ESQUERDA: class extends self.ISpriteInstance {},
	VIDA_HUD: class extends self.ISpriteInstance {},
	BACKGROUND: class extends self.ISpriteInstance {},
	SLASH: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	DEATHFORADOMAPA: class extends self.ISpriteInstance {},
	explosion: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	BACKGROUND2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	ESQUELETADO2: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	NightWalker: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Particles5: class extends self.IParticlesInstance {},
	Particles6: class extends self.IParticlesInstance {},
	Particles7: class extends self.IParticlesInstance {},
	Particles8: class extends self.IParticlesInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Button2: class extends self.IButtonInstance {},
	Mouse: class extends self.IInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sensor2: class extends self.ISpriteInstance {},
	Particles9: class extends self.IParticlesInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	RECOMEÇAR: class extends self.IButtonInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {}
}